---
title: "Background"
---

# Timeline

By displaying\

## The Dawn of Open Source AI

| Date       | Event                                                                                                                                                                       | Significance |
|------------------|---------------------------|---------------------------|
| 2023-02-24 | [Meta launches Large Language Model Meta AI (LLaMA) and open sources code without model weights.](https://ai.facebook.com/blog/large-language-model-llama-meta-ai/)         |              |
| 2023-03-03 | [LLaMA weights are leaked and shared via torrent on the internet.](https://www.vice.com/en/article/xgwqgw/facebooks-powerful-large-language-model-leaks-online-4chan-llama) |              |
| 2023-03-12 | [Artem Andreenko is able to get LLaMA working the a Raspberry Pi](https://github.com/ggerganov/llama.cpp/issues/58)                                                         |              |
| 2023-03-13 | [Stanford releases Alpaca, the first minimal working example of fine-tuning LLaMA](https://crfm.stanford.edu/2023/03/13/alpaca.html)                                        |              |
| 2023-03-14 | Eric Wang releases [Alpaca-LoRA](https://github.com/tloen/alpaca-lora)                                                                                                      |              |
| 2023-03-18 |                                                                                                                                                                             |              |
| 2023-03-19 | [Vicuna](https://lmsys.org/blog/2023-03-30-vicuna/)                                                                                                                         | \~\$300      |
| 2023-03-25 | Nomic releases GPT4All                                                                                                                                                      |              |
| 2023-03-03 | Cerebras uses [μ-parameterization](https://arxiv.org/abs/2203.03466)                                                                                                        |              |
| 2023-03-28 | LLaMA-Adapter uses Parameter Efficient Fine Tuning (PEFT)                                                                                                                   |              |
| 2023-04-03 | [Koala](https://bair.berkeley.edu/blog/2023/04/03/koala/)                                                                                                                   |              |
| 2023-04-15 | Open Assistant https://drive.google.com/file/d/10iR5hKwFqAKhL3umx8muOWSRm7hs5FqX/view                                                                                       | \$100        |

: Events from February 24, 2023 to April 15, 2023

## The Era of Democratized AI

| Date | Event                                                  | Significance                                                                                                                                                                                                                                                                                                                           |
|------------------|---------------------------|---------------------------|
|      | [LangChain](https://github.com/hwchase17/langchain)    | A library to assist in the development of data-aware agentic LLM applications by including multiple LLMs combined with other sources of information. Examples include Q&A over specific documents, databases, or APIs; chatbots that can reason before responding; agents that have control over system environments to perform tasks. |
|      | [LLamaIndex](https://github.com/jerryjliu/llama_index) |                                                                                                                                                                                                                                                                                                                                        |
|      | GPTCache                                               |                                                                                                                                                                                                                                                                                                                                        |
|      | LocalAI                                                |                                                                                                                                                                                                                                                                                                                                        |
|      | PandasAI                                               |                                                                                                                                                                                                                                                                                                                                        |