project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

execute:
  freeze: auto

website:

  page-navigation: true

  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
    right:
      - icon: github
        href: https://google.com
        aria-label: Polyphemus GitHub

  navbar:
    background: dark
    collapse-below: lg
    left:
      - text: "Background"
        href: background/index.html
      - text: "Models"
        href: models/index.html
      - text: "References"
        menu:
        - text: "FAQ"
          icon: "question-circle"
          href: faq/index.html