project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

execute:
  freeze: auto

website:

  page-navigation: true

  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
    right:
      - icon: twitter
        href: https://google.com
        aria-label: Polyphemus Twitter
      - icon: github
        href: https://google.com
        aria-label: Polyphemus GitHub
      - icon: rss
        href: https://google.com
        aria-label: Polyphemus Blog RSS

  navbar:
    background: dark
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Help"
        menu:
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd