site_name: Polyphemus
site_url: https://example.com/

nav:
    - Home: index.md
    
    - User Guide: user-guide/
    - Developer Guide: dev-guide/
    - About:
        - Background: about/background.md
        - Contributing: about/contributing.md

theme: readthedocs

copyright: Copyright &copy; 2023 Polyphemus
