on:
  workflow_dispatch:
  push:
    branches: main

name: Poetry Check

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Poetry
        run: |
          apt-get update && apt-get install --no-install-recommends -y curl build-essential
          curl -sSL https://install.python-poetry.org | python3 -
          source $HOME/.poetry/env
      - name: Check Poetry
        run: |
          poetry check
          poetry install
